ALTER TYPE language ADD VALUE IF NOT EXISTS 'kk';
ALTER TYPE language ADD VALUE IF NOT EXISTS 'uz';
ALTER TYPE language ADD VALUE IF NOT EXISTS 'tk';
ALTER TYPE language ADD VALUE IF NOT EXISTS 'zh-CN';
ALTER TYPE language ADD VALUE IF NOT EXISTS 'hi';
