import type { KnowledgeDocument, Source, StepDefinition } from '../../domain/src/index.js';
import { DIRECTORY_CHECKED_AT } from './directory.js';

export const commonSources: readonly Source[] = [
  {
    id: 'rf_registration_rules',
    title: 'Правила регистрации граждан Российской Федерации',
    url: 'https://epp.genproc.gov.ru/ru/proc_71/activity/legal-education/explain/e8518194/',
    authority: 'Прокуратура Тульской области',
    languages: ['ru'],
    validAsOf: DIRECTORY_CHECKED_AT,
    verificationStatus: 'verified',
  },
  {
    id: 'rf_military_accounting',
    title: 'Федеральный закон о воинской обязанности и военной службе',
    url: 'https://epp.genproc.gov.ru/ru/proc_szfo/activity/legal-education/explain/e5881282/',
    authority: 'Управление Генеральной прокуратуры по Северо-Западному федеральному округу',
    languages: ['ru'],
    validAsOf: DIRECTORY_CHECKED_AT,
    verificationStatus: 'verified',
  },
  {
    id: 'rf_foreign_migration',
    title: 'Федеральный закон о миграционном учёте иностранных граждан',
    url: 'https://epp.genproc.gov.ru/ru/proc_02/activity/legal-education/explain/e93627/',
    authority: 'Прокуратура Республики Башкортостан',
    languages: ['ru'],
    validAsOf: DIRECTORY_CHECKED_AT,
    verificationStatus: 'verified',
  },
  {
    id: 'rf_medical_2026',
    title: 'МВД России: изменения медосвидетельствования с 1 сентября 2026 года',
    url: 'https://mvdmedia.ru/news/official/irina-volk-v-sentyabre-2026-goda-vstupaet-v-silu-ryad-izmeneniy-v-rossiyskom-zakonodatelstve/',
    authority: 'МВД России',
    languages: ['ru'],
    validAsOf: '2026-09-24',
    verificationStatus: 'verified',
  },
  {
    id: 'rf_amina_2026',
    title: 'Департамент здравоохранения Москвы: кому подходит «Амина»',
    url: 'https://www.dgp86.ru/amina',
    authority: 'Департамент здравоохранения Москвы',
    languages: ['ru'],
    validAsOf: '2026-09-24',
    verificationStatus: 'verified',
  },
];

const common = {
  universityCode: null,
  whyImportantKey: 'steps.common.why',
  preparationKeys: [],
  contactKey: 'contact.university.instruction',
  validAsOf: DIRECTORY_CHECKED_AT,
  verificationStatus: 'needs_confirmation' as const,
  prerequisites: [],
  deadlineRule: null,
  deadlineNoteKey: 'deadline.to_be_confirmed',
  attention: 'normal' as const,
};

export const commonStepDefinitions: readonly StepDefinition[] = [
  {
    ...common,
    code: 'CONFIRM_ENROLLMENT',
    stage: 'pre_arrival',
    titleKey: 'steps.common.enrollment.title',
    descriptionKey: 'steps.common.enrollment.description',
    sourceId: null,
    sortOrder: 10,
    applicability: { enrollmentStates: ['awaiting_order'] },
  },
  {
    ...common,
    code: 'CHECK_HOUSING_STATUS',
    stage: 'pre_arrival',
    titleKey: 'steps.common.housing.title',
    descriptionKey: 'steps.common.housing.description',
    sourceId: null,
    sortOrder: 20,
    applicability: { mobilityStatuses: ['moving', 'moved'], housingStatuses: ['unknown', 'applied'] },
  },
  {
    ...common,
    code: 'CHECK_RF_REGISTRATION',
    stage: 'first_30_days',
    titleKey: 'steps.common.rf_registration.title',
    descriptionKey: 'steps.common.rf_registration.description',
    sourceId: 'rf_registration_rules',
    sortOrder: 30,
    applicability: { citizenshipTypes: ['rf'], mobilityStatuses: ['moving', 'moved'] },
  },
  {
    ...common,
    code: 'CHECK_MILITARY_STATUS',
    stage: 'first_30_days',
    titleKey: 'steps.common.military.title',
    descriptionKey: 'steps.common.military.description',
    sourceId: 'rf_military_accounting',
    sortOrder: 40,
    applicability: { citizenshipTypes: ['rf'], militaryStatuses: ['yes', 'unknown'] },
  },
  {
    ...common,
    code: 'CHECK_FOREIGN_ENTRY',
    stage: 'pre_arrival',
    titleKey: 'steps.common.foreign_entry.title',
    descriptionKey: 'steps.common.foreign_entry.description',
    sourceId: 'rf_foreign_migration',
    sortOrder: 15,
    applicability: {
      citizenshipTypes: ['foreign'],
      entryModes: ['unknown', 'already_in_russia'],
      russiaPresences: ['no', 'unknown'],
      arrivalStatuses: ['preparing'],
    },
  },
  {
    ...common,
    code: 'CHECK_VISA_ENTRY',
    stage: 'pre_arrival',
    titleKey: 'steps.common.visa_entry.title',
    descriptionKey: 'steps.common.visa_entry.description',
    sourceId: 'rf_foreign_migration',
    sortOrder: 15,
    applicability: {
      citizenshipTypes: ['foreign'],
      entryModes: ['visa'],
      russiaPresences: ['no'],
      arrivalStatuses: ['preparing'],
    },
  },
  {
    ...common,
    code: 'CHECK_VISA_FREE_ENTRY',
    stage: 'pre_arrival',
    titleKey: 'steps.common.visa_free_entry.title',
    descriptionKey: 'steps.common.visa_free_entry.description',
    sourceId: 'rf_foreign_migration',
    sortOrder: 15,
    applicability: {
      citizenshipTypes: ['foreign'],
      entryModes: ['visa_free'],
      russiaPresences: ['no'],
      arrivalStatuses: ['preparing'],
    },
  },
  {
    ...common,
    code: 'CHECK_CURRENT_STAY',
    stage: 'pre_arrival',
    titleKey: 'steps.common.current_stay.title',
    descriptionKey: 'steps.common.current_stay.description',
    sourceId: 'rf_foreign_migration',
    sortOrder: 15,
    applicability: { citizenshipTypes: ['foreign'], russiaPresences: ['yes'], arrivalStatuses: ['preparing'] },
  },
  {
    ...common,
    code: 'CHECK_FOREIGN_STAY',
    stage: 'first_three_days',
    titleKey: 'steps.common.foreign_stay.title',
    descriptionKey: 'steps.common.foreign_stay.description',
    sourceId: 'rf_foreign_migration',
    sortOrder: 12,
    attention: 'high',
    applicability: { citizenshipTypes: ['foreign'], russiaPresences: ['yes'] },
  },
  {
    ...common,
    code: 'CHECK_MEDICAL_2026',
    stage: 'first_30_days',
    titleKey: 'steps.common.medical_2026.title',
    descriptionKey: 'steps.common.medical_2026.description',
    sourceId: 'rf_medical_2026',
    sortOrder: 52,
    applicability: { citizenshipTypes: ['foreign'], russiaPresences: ['yes'] },
  },
  {
    ...common,
    code: 'CHECK_AMINA_ELIGIBILITY',
    stage: 'first_three_days',
    titleKey: 'steps.common.amina.title',
    descriptionKey: 'steps.common.amina.description',
    sourceId: 'rf_amina_2026',
    sortOrder: 48,
    applicability: {
      universityCodes: ['MSU', 'MEPHI', 'MIPT', 'HSE', 'RUDN'],
      campusCodes: ['main'],
      citizenshipTypes: ['foreign'],
      entryModes: ['visa_free'],
      russiaPresences: ['yes'],
      accommodationTypes: ['private', 'relatives'],
      arrivalStatuses: ['arrived'],
    },
  },
];

export const commonKnowledgeDocuments: readonly KnowledgeDocument[] = [
  {
    id: 'kb-common-medical-2026-ru',
    title: 'Медосвидетельствование иностранного студента после въезда',
    content:
      'С 1 сентября 2026 года для иностранца, прибывшего более чем на 90 календарных дней, МВД указывает 30 календарных дней со дня въезда на медицинское освидетельствование. Проверить применимость, исключения и наличие прежнего действующего заключения нужно по личному статусу. Срок дактилоскопии — отдельный вопрос: противоречащие памятки вузов не позволяют вычислить его здесь.',
    sourceId: 'rf_medical_2026',
    language: 'ru',
    tags: ['медицина', 'освидетельствование', 'въезд'],
    validAsOf: '2026-09-24',
  },
  {
    id: 'kb-common-medical-2026-en',
    title: 'Medical examination after entry',
    content:
      'From 1 September 2026, the Russian Interior Ministry states a 30-calendar-day medical examination period after entry for foreigners coming for more than 90 calendar days. Check applicability, exceptions and any valid prior examination for your own status. Fingerprinting is separate; conflicting university guides do not justify an automatic date here.',
    sourceId: 'rf_medical_2026',
    language: 'en',
    tags: ['medical', 'examination', 'entry'],
    validAsOf: '2026-09-24',
  },
  {
    id: 'kb-common-amina-2026-ru',
    title: '«Амина» для части иностранных студентов Москвы и Подмосковья',
    content:
      'С сентября 2026 года «Амина» может относиться к совершеннолетнему безвизовому иностранцу с нерабочей целью и пребыванием более 90 дней в Москве или Московской области, если он живёт в частном жилье и не имеет РВП или ВНЖ. Общежития и гостиницы исключены: учёт выполняет администрация. Гражданство Беларуси также исключено. Проверьте все условия до регистрации в приложении.',
    sourceId: 'rf_amina_2026',
    language: 'ru',
    tags: ['Амина', 'Москва', 'миграция', 'жильё'],
    validAsOf: '2026-09-24',
  },
  {
    id: 'kb-common-amina-2026-en',
    title: 'Amina for some international students in Moscow and the region',
    content:
      'From September 2026, Amina may apply to adults entering visa-free for non-work purposes for over 90 days in Moscow or its region, living privately without a temporary or permanent residence permit. Dormitories and hotels are excluded; their administration handles registration. Belarusian citizens are also excluded. Check all conditions first.',
    sourceId: 'rf_amina_2026',
    language: 'en',
    tags: ['Amina', 'Moscow', 'migration', 'housing'],
    validAsOf: '2026-09-24',
  },
  {
    id: 'kb-common-rf-registration-ru',
    title: 'Регистрация граждан РФ при переезде',
    content:
      'Если вы временно живёте в другом городе более 90 дней, проверьте регистрацию по месту пребывания с собственником или общежитием; постоянная регистрация сохраняется. При смене именно места жительства действует отдельное правило обращения в течение семи дней. Уточните тип проживания, дату прибытия и исключения; это не два срока одной процедуры.',
    sourceId: 'rf_registration_rules',
    language: 'ru',
    tags: ['переезд', 'регистрация', 'жилье'],
    validAsOf: DIRECTORY_CHECKED_AT,
  },
  {
    id: 'kb-common-military-ru',
    title: 'Воинский учёт',
    content:
      'Воинский учёт зависит от вашей обязанности состоять на учёте, а не только от пола. Если вы подлежите учёту и переехали на новое место пребывания, официальное разъяснение называет двухнедельный срок сообщения о переезде письменно или через Госуслуги. Уточните свой статус и дату применимого события; учёба сама по себе не означает отсрочку.',
    sourceId: 'rf_military_accounting',
    language: 'ru',
    tags: ['воинский', 'учет', 'переезд'],
    validAsOf: DIRECTORY_CHECKED_AT,
  },
  {
    id: 'kb-common-foreign-ru',
    title: 'Миграционный учёт после въезда',
    content:
      'Обычно уведомление о прибытии по фактическому адресу подаёт принимающая сторона в течение семи рабочих дней. Для отдельных гражданств и статусов есть исключения; университет может просить передать документы студентом раньше. Уточните гражданство, жильё и принимающую сторону: семь рабочих дней не универсальный личный срок.',
    sourceId: 'rf_foreign_migration',
    language: 'ru',
    tags: ['миграция', 'регистрация', 'приезд'],
    validAsOf: DIRECTORY_CHECKED_AT,
  },
  {
    id: 'kb-common-rf-registration-en',
    title: 'Registration after moving within Russia',
    content:
      'If you temporarily stay in another city for more than 90 days, check registration at that address with your landlord or dormitory; permanent registration remains. Changing your actual place of residence has a separate seven-day rule. Confirm your housing type, arrival date and exceptions; these are not two deadlines for the same procedure.',
    sourceId: 'rf_registration_rules',
    language: 'en',
    tags: ['moving', 'registration', 'housing'],
    validAsOf: DIRECTORY_CHECKED_AT,
  },
  {
    id: 'kb-common-military-en',
    title: 'Military registration',
    content:
      'Military registration depends on whether you are liable to register, not sex alone. For a liable person moving to a new place of stay, the official explanation gives two weeks to report the move in writing or through Gosuslugi. Confirm your status and relevant event date; study does not itself guarantee deferment.',
    sourceId: 'rf_military_accounting',
    language: 'en',
    tags: ['military', 'registration', 'moving'],
    validAsOf: DIRECTORY_CHECKED_AT,
  },
  {
    id: 'kb-common-foreign-en',
    title: 'Migration registration after entry',
    content:
      'Usually the receiving host submits arrival notice for the actual address within seven working days. Some citizenships and statuses have exceptions; a university may ask the student to supply documents sooner. Confirm citizenship, housing and host: seven working days is not a universal personal deadline.',
    sourceId: 'rf_foreign_migration',
    language: 'en',
    tags: ['migration', 'registration', 'arrival'],
    validAsOf: DIRECTORY_CHECKED_AT,
  },
];
