import type { KnowledgeDocument, Source, StepDefinition, UniversityConfig } from '../../domain/src/index.js';
import { directoryUniversityConfigs } from './directory.js';

export const CONTENT_VALID_AS_OF = '2026-09-21';

export const itmoUniversityConfig: UniversityConfig = {
  code: 'ITMO',
  name: 'ITMO University',
  timezone: 'Europe/Moscow',
  supportedLanguages: ['ru', 'en'],
  disclaimerKey: 'app.disclaimer',
  officialContact: {
    labelKey: 'contact.official.label',
    instructionKey: 'contact.official.instruction',
    url: 'https://int.itmo.ru/en/contact_us',
    email: 'int.students@itmo.ru',
    phone: null,
  },
};

export const itmoSources: readonly Source[] = [
  {
    id: 'itmo_arrival_guide',
    title: 'Arrival Guide for First-Year Students',
    url: 'https://itmo.ru/images/pages_trans/206/Arrival_Guide_for_First-Year_Students.pdf',
    authority: 'ITMO University',
    languages: ['en'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
  {
    id: 'itmo_migration_documents',
    title: 'Important Documents',
    url: 'https://int.itmo.ru/en/important_documents',
    authority: 'ITMO International',
    languages: ['en'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
  {
    id: 'itmo_migration_documents_ru',
    title: 'Миграционные документы',
    url: 'https://int.itmo.ru/ru/important_documents',
    authority: 'ИТМО',
    languages: ['ru'],
    validAsOf: '2026-09-23',
    verificationStatus: 'verified',
  },
  {
    id: 'itmo_international_contacts',
    title: 'Contact Us',
    url: 'https://int.itmo.ru/en/contact_us',
    authority: 'ITMO International',
    languages: ['en'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
  {
    id: 'itmo_dorm_booking',
    title: 'Moving into a Dormitory',
    url: 'https://student.itmo.ru/en/campus/dorms_and_aparts/booking',
    authority: 'ITMO.STUDENTS',
    languages: ['en'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
  {
    id: 'itmo_housing',
    title: 'Dormitories and Apartments',
    url: 'https://student.itmo.ru/en/campus/dorms_and_aparts',
    authority: 'ITMO.STUDENTS',
    languages: ['en'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
  {
    id: 'itmo_student_services',
    title: 'Заказ и получение документов ИТМО',
    url: 'https://student.itmo.ru/ru/services/documents',
    authority: 'ITMO.STUDENTS',
    languages: ['ru'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
  {
    id: 'itmo_buddy',
    title: 'Buddy System',
    url: 'https://int.itmo.ru/en/buddy_system',
    authority: 'ITMO International',
    languages: ['en'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
  {
    id: 'rf_migration_law_109',
    title: 'Federal Law No. 109-FZ',
    url: 'https://epp.genproc.gov.ru/ru/proc_02/activity/legal-education/explain/e93627/',
    authority: 'Прокуратура Республики Башкортостан',
    languages: ['ru'],
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'verified',
  },
] as const;

const commonDeadline = {
  deadlineRule: null,
  deadlineNoteKey: 'deadline.to_be_confirmed',
} as const;

/**
 * Ten stable definitions produce nine active dormitory steps and eight active
 * private/relatives steps. Legal applicability and exact dates are deliberately
 * delegated to official personalised guidance.
 */
const foreignItmoSteps: readonly StepDefinition[] = [
  {
    code: 'CHECK_ENTRY_REQUIREMENTS',
    universityCode: 'ITMO',
    stage: 'pre_arrival',
    titleKey: 'steps.check_entry_requirements.title',
    descriptionKey: 'steps.check_entry_requirements.description',
    whyImportantKey: 'steps.check_entry_requirements.why',
    preparationKeys: ['steps.check_entry_requirements.prepare'],
    contactKey: 'contact.migration',
    sourceId: 'itmo_arrival_guide',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 10,
    prerequisites: [],
    applicability: { arrivalStatuses: ['preparing'] },
    ...commonDeadline,
    attention: 'high',
  },
  {
    code: 'NOTIFY_PLANNED_ARRIVAL',
    universityCode: 'ITMO',
    stage: 'pre_arrival',
    titleKey: 'steps.notify_planned_arrival.title',
    descriptionKey: 'steps.notify_planned_arrival.description',
    whyImportantKey: 'steps.notify_planned_arrival.why',
    preparationKeys: ['steps.notify_planned_arrival.prepare'],
    contactKey: 'contact.international',
    sourceId: 'itmo_international_contacts',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 20,
    prerequisites: ['CHECK_ENTRY_REQUIREMENTS'],
    applicability: { arrivalStatuses: ['preparing'] },
    ...commonDeadline,
    attention: 'normal',
  },
  {
    code: 'ARRANGE_DORMITORY',
    universityCode: 'ITMO',
    stage: 'pre_arrival',
    titleKey: 'steps.arrange_dormitory.title',
    descriptionKey: 'steps.arrange_dormitory.description',
    whyImportantKey: 'steps.arrange_dormitory.why',
    preparationKeys: ['steps.arrange_dormitory.prepare'],
    contactKey: 'contact.dormitory',
    sourceId: 'itmo_dorm_booking',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 30,
    prerequisites: ['NOTIFY_PLANNED_ARRIVAL'],
    applicability: { accommodationTypes: ['dormitory'] },
    ...commonDeadline,
    attention: 'normal',
  },
  {
    code: 'OBTAIN_HEALTH_INSURANCE',
    universityCode: 'ITMO',
    stage: 'pre_arrival',
    titleKey: 'steps.obtain_health_insurance.title',
    descriptionKey: 'steps.obtain_health_insurance.description',
    whyImportantKey: 'steps.obtain_health_insurance.why',
    preparationKeys: ['steps.obtain_health_insurance.prepare'],
    contactKey: 'contact.international',
    sourceId: 'itmo_arrival_guide',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 40,
    prerequisites: ['CHECK_ENTRY_REQUIREMENTS'],
    applicability: {},
    ...commonDeadline,
    attention: 'normal',
  },
  {
    code: 'CHECK_BORDER_DOCUMENTS',
    universityCode: 'ITMO',
    stage: 'first_three_days',
    titleKey: 'steps.check_border_documents.title',
    descriptionKey: 'steps.check_border_documents.description',
    whyImportantKey: 'steps.check_border_documents.why',
    preparationKeys: ['steps.check_border_documents.prepare'],
    contactKey: 'contact.migration',
    sourceId: 'itmo_migration_documents',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 50,
    prerequisites: ['CHECK_ENTRY_REQUIREMENTS'],
    applicability: {},
    ...commonDeadline,
    attention: 'high',
  },
  {
    code: 'REGISTER_DORM_RESIDENCE',
    universityCode: 'ITMO',
    stage: 'first_three_days',
    titleKey: 'steps.register_dorm_residence.title',
    descriptionKey: 'steps.register_dorm_residence.description',
    whyImportantKey: 'steps.register_dorm_residence.why',
    preparationKeys: ['steps.register_dorm_residence.prepare'],
    contactKey: 'contact.dormitory',
    sourceId: 'itmo_arrival_guide',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 60,
    prerequisites: ['CHECK_BORDER_DOCUMENTS'],
    applicability: { accommodationTypes: ['dormitory'] },
    ...commonDeadline,
    attention: 'high',
  },
  {
    code: 'REGISTER_PRIVATE_RESIDENCE',
    universityCode: 'ITMO',
    stage: 'first_three_days',
    titleKey: 'steps.register_private_residence.title',
    descriptionKey: 'steps.register_private_residence.description',
    whyImportantKey: 'steps.register_private_residence.why',
    preparationKeys: ['steps.register_private_residence.prepare'],
    contactKey: 'contact.migration',
    sourceId: 'itmo_migration_documents',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 60,
    prerequisites: ['CHECK_BORDER_DOCUMENTS'],
    applicability: { accommodationTypes: ['private', 'relatives'] },
    ...commonDeadline,
    attention: 'high',
  },
  {
    code: 'CHECK_MIGRATION_PROCEDURES',
    universityCode: 'ITMO',
    stage: 'first_week',
    titleKey: 'steps.check_migration_procedures.title',
    descriptionKey: 'steps.check_migration_procedures.description',
    whyImportantKey: 'steps.check_migration_procedures.why',
    preparationKeys: ['steps.check_migration_procedures.prepare'],
    contactKey: 'contact.migration',
    sourceId: 'itmo_migration_documents',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'needs_confirmation',
    sortOrder: 70,
    prerequisites: ['CHECK_BORDER_DOCUMENTS'],
    applicability: {},
    ...commonDeadline,
    attention: 'high',
  },
  {
    code: 'COMPLETE_FIRST_DAYS',
    universityCode: 'ITMO',
    stage: 'first_week',
    titleKey: 'steps.complete_first_days.title',
    descriptionKey: 'steps.complete_first_days.description',
    whyImportantKey: 'steps.complete_first_days.why',
    preparationKeys: ['steps.complete_first_days.prepare'],
    contactKey: 'contact.student_services',
    sourceId: 'itmo_student_services',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'demo',
    sortOrder: 80,
    prerequisites: ['NOTIFY_PLANNED_ARRIVAL'],
    applicability: {},
    ...commonDeadline,
    attention: 'normal',
  },
  {
    code: 'ORIENTATION_SUPPORT',
    universityCode: 'ITMO',
    stage: 'first_30_days',
    titleKey: 'steps.orientation_support.title',
    descriptionKey: 'steps.orientation_support.description',
    whyImportantKey: 'steps.orientation_support.why',
    preparationKeys: ['steps.orientation_support.prepare'],
    contactKey: 'contact.student_services',
    sourceId: 'itmo_buddy',
    validAsOf: CONTENT_VALID_AS_OF,
    verificationStatus: 'demo',
    sortOrder: 90,
    prerequisites: ['COMPLETE_FIRST_DAYS'],
    applicability: {},
    ...commonDeadline,
    attention: 'normal',
  },
] as const;

export const itmoStepDefinitions: readonly StepDefinition[] = foreignItmoSteps.map((step) => ({
  ...step,
  applicability: { ...step.applicability, citizenshipTypes: ['foreign'] },
}));

export const itmoKnowledgeDocuments: readonly KnowledgeDocument[] = [
  {
    id: 'kb-en-arrival',
    title: 'Preparing for arrival',
    content:
      'Review the current ITMO arrival guide and the instructions sent with your admission correspondence. Confirm requirements for your personal situation with the international student support team.',
    sourceId: 'itmo_arrival_guide',
    language: 'en',
    tags: ['arrival', 'entry', 'insurance', 'documents'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
  {
    id: 'kb-ru-arrival',
    title: 'Подготовка к приезду',
    content:
      'Проверьте актуальную памятку ИТМО о приезде и инструкции из писем о поступлении. Требования для вашего случая уточните в службе поддержки иностранных студентов.',
    sourceId: 'itmo_arrival_guide',
    language: 'ru',
    tags: ['приезд', 'въезд', 'страховка', 'документы'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
  {
    id: 'kb-en-dormitory',
    title: 'Dormitory arrangements',
    content:
      "Use ITMO's official dormitory booking page and your individual correspondence to confirm whether accommodation is assigned, where to arrive, and which current instructions apply.",
    sourceId: 'itmo_dorm_booking',
    language: 'en',
    tags: ['dormitory', 'housing', 'booking', 'check-in'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
  {
    id: 'kb-ru-dormitory',
    title: 'Общежитие',
    content:
      'Используйте официальную страницу ИТМО по общежитиям и личную переписку, чтобы уточнить назначение, место приезда и текущие инструкции.',
    sourceId: 'itmo_dorm_booking',
    language: 'ru',
    tags: ['общежитие', 'жилье', 'бронирование', 'заселение'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
  {
    id: 'kb-en-migration',
    title: 'Migration document guidance',
    content:
      'ITMO International publishes an official overview of important documents. Because applicability and timing can depend on individual circumstances, confirm your personal next action with the responsible office.',
    sourceId: 'itmo_migration_documents',
    language: 'en',
    tags: ['migration', 'registration', 'documents', 'residence'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
  {
    id: 'kb-ru-migration',
    title: 'Миграционные документы',
    content:
      'Иностранному студенту ИТМО после въезда нужно проверить документ, удостоверяющий личность, миграционную карту, если её выдавали, и подтверждение миграционного учёта. Если вы живёте в общежитии ИТМО, передайте документ въезда и миграционную карту в отдел миграционного учёта на Ломоносова, 9, офис 2139d; при платном обучении также нужен договор. Если живёте по частному адресу, учёт оформляет принимающая сторона по фактическому адресу. Срок передачи документов в вуз и федеральный срок учёта — разные вопросы; уточните их для своего гражданства и жилья.',
    sourceId: 'itmo_migration_documents_ru',
    language: 'ru',
    tags: ['миграция', 'регистрация', 'документы', 'проживание'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
  {
    id: 'kb-en-support',
    title: 'Official contact',
    content:
      "For a personalised answer, use ITMO International's current Contact Us page. The service should hand off questions when the local knowledge base has insufficient evidence.",
    sourceId: 'itmo_international_contacts',
    language: 'en',
    tags: ['contact', 'support', 'email', 'help'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
  {
    id: 'kb-ru-support',
    title: 'Куда обратиться в ИТМО',
    content:
      'Для ответа с учётом вашей ситуации используйте актуальную страницу контактов ИТМО. Если в доступных материалах нет достаточных данных, обратитесь к сотруднику университета.',
    sourceId: 'itmo_international_contacts',
    language: 'ru',
    tags: ['контакт', 'поддержка', 'почта', 'помощь'],
    validAsOf: CONTENT_VALID_AS_OF,
  },
] as const;

export const itmoConfig = {
  university: itmoUniversityConfig,
  sources: itmoSources,
  stepDefinitions: itmoStepDefinitions,
  knowledgeDocuments: itmoKnowledgeDocuments,
} as const;

export const universityConfigs: Readonly<Record<string, UniversityConfig>> = {
  ...directoryUniversityConfigs,
  ITMO: itmoUniversityConfig,
  OTHER: {
    code: 'OTHER',
    name: 'Университет не в справочнике',
    timezone: 'Europe/Moscow',
    supportedLanguages: ['ru', 'en'],
    disclaimerKey: 'app.disclaimer',
    officialContact: {
      labelKey: 'contact.university.label',
      instructionKey: 'contact.university.instruction',
      url: null,
      email: null,
      phone: null,
    },
  },
};

export function getUniversityConfig(code: string): UniversityConfig | null {
  return universityConfigs[code] ?? null;
}
