import type { OnboardingFlow } from '../../domain/src/index.js';

export const onboardingFlow: OnboardingFlow = {
  id: 'student_onboarding_v4',
  firstQuestionId: 'ONB_01_LANGUAGE',
  questions: [
    {
      id: 'ONB_01_LANGUAGE',
      textKey: 'onboarding.language.question',
      type: 'single_choice',
      options: [
        { labelKey: 'language.ru', value: 'ru' },
        { labelKey: 'language.en', value: 'en' },
        { labelKey: 'language.kk', value: 'kk' },
        { labelKey: 'language.uz', value: 'uz' },
        { labelKey: 'language.tk', value: 'tk' },
        { labelKey: 'language.zh-CN', value: 'zh-CN' },
        { labelKey: 'language.hi', value: 'hi' },
      ],
      targetField: 'preferredLanguage',
      required: true,
      next: 'ONB_02_UNIVERSITY',
      conditions: [],
    },
    {
      id: 'ONB_02_UNIVERSITY',
      textKey: 'onboarding.university.question',
      type: 'single_choice',
      options: [
        { labelKey: 'university.msu', value: 'MSU' },
        { labelKey: 'university.mephi', value: 'MEPHI' },
        { labelKey: 'university.mipt', value: 'MIPT' },
        { labelKey: 'university.hse', value: 'HSE' },
        { labelKey: 'university.nsu', value: 'NSU' },
        { labelKey: 'university.spbu', value: 'SPBU' },
        { labelKey: 'university.tsu', value: 'TSU' },
        { labelKey: 'university.itmo', value: 'ITMO' },
        { labelKey: 'university.kfu', value: 'KFU' },
        { labelKey: 'university.rudn', value: 'RUDN' },
        { labelKey: 'university.other', value: 'OTHER' },
      ],
      targetField: 'universityCode',
      required: true,
      next: 'ONB_02_CAMPUS',
      conditions: [],
    },
    {
      id: 'ONB_02_CAMPUS',
      textKey: 'onboarding.campus.question',
      type: 'single_choice',
      options: [
        { labelKey: 'campus.main', value: 'main' },
        { labelKey: 'campus.spb', value: 'spb' },
        { labelKey: 'campus.nnov', value: 'nnov' },
        { labelKey: 'campus.perm', value: 'perm' },
        { labelKey: 'campus.peterhof', value: 'peterhof' },
        { labelKey: 'campus.other', value: 'other' },
      ],
      targetField: 'campusCode',
      required: true,
      next: 'ONB_02_MSU_FACULTY',
      conditions: [],
    },
    {
      id: 'ONB_02_MSU_FACULTY',
      textKey: 'onboarding.msu_faculty.question',
      type: 'single_choice',
      options: [
        { labelKey: 'faculty.msu_econ', value: 'msu_econ' },
        { labelKey: 'faculty.msu_soil', value: 'msu_soil' },
        { labelKey: 'faculty.other', value: 'other' },
        { labelKey: 'faculty.unknown', value: 'unknown' },
      ],
      targetField: 'facultyCode',
      required: true,
      next: 'ONB_02_TSU_FACULTY',
      conditions: [{ field: 'universityCode', op: 'eq', value: 'MSU' }],
    },
    {
      id: 'ONB_02_TSU_FACULTY',
      textKey: 'onboarding.tsu_faculty.question',
      type: 'single_choice',
      options: [
        { labelKey: 'faculty.tsu_law', value: 'tsu_law' },
        { labelKey: 'faculty.other', value: 'other' },
        { labelKey: 'faculty.unknown', value: 'unknown' },
      ],
      targetField: 'facultyCode',
      required: true,
      next: 'ONB_02_OTHER_UNIVERSITY',
      conditions: [{ field: 'universityCode', op: 'eq', value: 'TSU' }],
    },
    {
      id: 'ONB_02_OTHER_UNIVERSITY',
      textKey: 'onboarding.other_university.question',
      type: 'text',
      targetField: 'universityName',
      required: true,
      next: 'ONB_03_CITIZENSHIP',
      conditions: [{ field: 'universityCode', op: 'eq', value: 'OTHER' }],
    },
    {
      id: 'ONB_03_CITIZENSHIP',
      textKey: 'onboarding.country.question',
      type: 'text',
      options: [{ labelKey: 'country.russia', value: 'RU' }],
      targetField: 'citizenshipCountry',
      required: true,
      next: 'ONB_04_SPECIAL_STATUS',
      conditions: [],
    },
    {
      id: 'ONB_04_SPECIAL_STATUS',
      textKey: 'onboarding.special_status.question',
      type: 'single_choice',
      options: [
        { labelKey: 'special_status.none', value: 'none' },
        { labelKey: 'special_status.rvp', value: 'rvp' },
        { labelKey: 'special_status.rvpo', value: 'rvpo' },
        { labelKey: 'special_status.vnj', value: 'vnj' },
        { labelKey: 'special_status.unknown', value: 'unknown' },
      ],
      targetField: 'specialStatus',
      required: true,
      next: 'ONB_05_ARRIVAL_STATUS',
      conditions: [{ field: 'citizenshipType', op: 'eq', value: 'foreign' }],
    },
    {
      id: 'ONB_05_ARRIVAL_STATUS',
      textKey: 'onboarding.in_russia.question',
      type: 'single_choice',
      options: [
        { labelKey: 'arrival.arrived', value: 'arrived' },
        { labelKey: 'arrival.preparing', value: 'preparing' },
      ],
      targetField: 'arrivalStatus',
      required: true,
      next: 'ONB_06_PLANNED_DATE',
      conditions: [],
    },
    {
      id: 'ONB_06_PLANNED_DATE',
      textKey: 'onboarding.planned_date.question',
      type: 'date',
      targetField: 'arrivalDate',
      required: false,
      next: 'ONB_06_ENTRY_DATE',
      conditions: [{ field: 'arrivalStatus', op: 'eq', value: 'preparing' }],
    },
    {
      id: 'ONB_06_ENTRY_DATE',
      textKey: 'onboarding.entry_date.question',
      type: 'date',
      targetField: 'arrivalDate',
      required: false,
      next: 'ONB_07_ACCOMMODATION',
      conditions: [{ field: 'arrivalStatus', op: 'eq', value: 'arrived' }],
    },
    {
      id: 'ONB_07_ACCOMMODATION',
      textKey: 'onboarding.housing.question',
      type: 'single_choice',
      options: [
        { labelKey: 'accommodation.dormitory', value: 'dormitory' },
        { labelKey: 'accommodation.private', value: 'private' },
        { labelKey: 'accommodation.relatives_full', value: 'relatives' },
        { labelKey: 'accommodation.hotel', value: 'hotel' },
        { labelKey: 'accommodation.other', value: 'other' },
        { labelKey: 'accommodation.unknown', value: 'unknown' },
      ],
      targetField: 'housingChoice',
      required: true,
      next: 'ONB_08_ADMISSION_YEAR',
      conditions: [],
    },
    {
      id: 'ONB_08_ADMISSION_YEAR',
      textKey: 'onboarding.admission_year.question',
      type: 'single_choice',
      options: [
        { labelKey: 'admission_year.2026', value: '2026' },
        { labelKey: 'admission_year.2027', value: '2027' },
        { labelKey: 'admission_year.unknown', value: 'unknown' },
      ],
      targetField: 'admissionYear',
      required: true,
      next: 'ONB_09_ENTRY_MODE',
      conditions: [],
    },
    {
      id: 'ONB_09_ENTRY_MODE',
      textKey: 'onboarding.entry_mode.question',
      type: 'single_choice',
      options: [
        { labelKey: 'entry.visa', value: 'visa' },
        { labelKey: 'entry.visa_free', value: 'visa_free' },
        { labelKey: 'entry.already_in_russia', value: 'already_in_russia' },
        { labelKey: 'entry.unknown', value: 'unknown' },
      ],
      targetField: 'entryMode',
      required: true,
      next: 'ONB_10_HOUSING_STATUS',
      conditions: [{ field: 'citizenshipType', op: 'eq', value: 'foreign' }],
    },
    {
      id: 'ONB_10_HOUSING_STATUS',
      textKey: 'onboarding.housing_status.question',
      type: 'single_choice',
      options: [
        { labelKey: 'housing.confirmed', value: 'confirmed' },
        { labelKey: 'housing.applied', value: 'applied' },
        { labelKey: 'housing.unknown', value: 'unknown' },
      ],
      targetField: 'housingStatus',
      required: true,
      next: 'ONB_11_MOBILITY',
      conditions: [{ field: 'housingChoice', op: 'eq', value: 'dormitory' }],
    },
    {
      id: 'ONB_11_MOBILITY',
      textKey: 'onboarding.mobility.question',
      type: 'single_choice',
      options: [
        { labelKey: 'mobility.local', value: 'local' },
        { labelKey: 'mobility.moving', value: 'moving' },
        { labelKey: 'mobility.moved', value: 'moved' },
        { labelKey: 'mobility.unknown', value: 'unknown' },
      ],
      targetField: 'mobilityStatus',
      required: true,
      next: 'ONB_12_PROGRAM_LEVEL',
      conditions: [],
    },
    {
      id: 'ONB_12_PROGRAM_LEVEL',
      textKey: 'onboarding.program_level.question',
      type: 'single_choice',
      options: [
        { labelKey: 'program.bachelor_specialist', value: 'bachelor_specialist' },
        { labelKey: 'program.masters', value: 'masters' },
        { labelKey: 'program.postgraduate', value: 'postgraduate' },
        { labelKey: 'program.unknown', value: 'unknown' },
      ],
      targetField: 'programLevel',
      required: true,
      next: null,
      conditions: [],
    },
  ],
};
