import type { ApplicabilityRule, RouteStage } from '../../domain/src/index.js';
import type { UniversityAction } from './university-actions.js';

/** Concrete procedures from the official pages checked in the 24 September research packet.
 * No date is inferred from an admission campaign or a university processing interval. */
const CHECKED_AT = '2026-09-24';
const action = (
  university: string,
  code: string,
  stage: RouteStage,
  titleRu: string,
  titleEn: string,
  actionRu: string,
  actionEn: string,
  sourceUrl: string,
  applicability: ApplicabilityRule,
  sortOrder: number,
  admissionYear?: number,
): UniversityAction => ({
  university,
  code,
  stage,
  titleRu,
  titleEn,
  actionRu,
  actionEn,
  sourceUrl,
  sourceTitle: titleRu,
  audienceRu: titleRu,
  audienceEn: titleEn,
  applicability,
  sortOrder,
  admissionYear,
  checkedAt: CHECKED_AT,
});

const foreign = { citizenshipTypes: ['foreign'] } as const;
const rf = { citizenshipTypes: ['rf'] } as const;
const dorm = { accommodationTypes: ['dormitory'] } as const;
const privateHousing = { accommodationTypes: ['private', 'relatives'] } as const;
const main = { campusCodes: ['main'] } as const;
const arrived = { arrivalStatuses: ['arrived'] } as const;

export const verifiedUniversityActions: readonly UniversityAction[] = [
  action(
    'MSU',
    'MSU_ECON_DORM_2026',
    'pre_arrival',
    'Получить ордер на общежитие экономического факультета МГУ',
    'Get the MSU Economics dormitory assignment',
    'Только для зачисленного в 2026 году на экономический факультет гражданина РФ с подтверждённым местом: запишитесь в электронную очередь, придите с паспортом в кабинет 240 факультета за ордером и выписками. Затем отправляйтесь в назначенное общежитие. Подготовьте паспорт с копиями, ордер, выписки и две фотографии 3×4; договор — при платном обучении, воинский документ — только при соответствующем статусе.',
    'Only for a Russian citizen admitted to the MSU Faculty of Economics in 2026 with a confirmed place: join the electronic queue and bring passport to faculty room 240 for your order and extracts. Then visit your assigned dormitory. Bring passport copies, order, extracts and two 3×4 photos; contract for fee-paying study, military document only when applicable.',
    'https://www.econ.msu.ru/students/life/hostel/',
    { ...rf, ...dorm, facultyCodes: ['msu_econ'], admissionYears: [2026], housingStatuses: ['confirmed'] },
    20,
    2026,
  ),
  action(
    'MSU',
    'MSU_SOIL_DORM_2026',
    'pre_arrival',
    'Оформить заселение факультета почвоведения МГУ',
    'Arrange MSU Soil Science dormitory move-in',
    'Только если место подтверждено факультетом почвоведения для набора 2026: списки передаются в ДАС без поездки за направлением на факультет. Обратитесь в паспортный стол ДАС: Москва, ул. Шверника, 19, корпус 2, кабинет 141. Возьмите паспорт и копию страницы с данными и регистрацией на одном листе, две матовые фотографии 3×4; воинский документ — при соответствующем статусе. Дату уточните в личном назначении.',
    'Only if the MSU Soil Science faculty confirmed your 2026 place: lists go directly to DAS. Visit DAS passport office at Shvernika 19 building 2 room 141, Moscow. Bring passport and registration copy on one sheet, two matte 3×4 photos, and military document when applicable. Confirm your personal date.',
    'https://soil.msu.ru/postuplenie/postupayushchim-v-bakalavriat/5370-poselenie-v-obshchezhitie-2026',
    { ...rf, ...dorm, facultyCodes: ['msu_soil'], admissionYears: [2026], housingStatuses: ['confirmed'] },
    20,
    2026,
  ),
  action(
    'MSU',
    'MSU_VISA_PACKAGE',
    'pre_arrival',
    'Получить приглашение через факультет МГУ',
    'Get a visa invitation through your MSU faculty',
    'Если вам нужна учебная виза, передайте иностранному отделу своего факультета анкету, согласие на обработку данных и скан первых страниц паспорта. После получения электронного приглашения проверьте визу и отправьте её скан факультету. Название факультета и его контакт найдите на странице МГУ; ориентир 25–45 дней не гарантирует дату готовности.',
    'If you need a study visa, send the application, consent and passport scan to your faculty international office. After receiving the invitation, check the visa and send its scan back. Find the correct faculty contact on the MSU site; the 25–45 day estimate is not a guaranteed date.',
    'https://international.msu.ru/before',
    { ...foreign, entryModes: ['visa'], arrivalStatuses: ['preparing'] },
    30,
  ),
  action(
    'MSU',
    'MSU_ARRIVAL_DOCUMENTS',
    'pre_arrival',
    'Подготовить документы для въезда в МГУ',
    'Prepare MSU arrival documents',
    'Перед поездкой уточните у иностранного отдела факультета медицинскую страховку и названные МГУ медицинские документы. Если вам нет 18 лет, спросите о нотариальном согласии родителей на медицинские процедуры и договор общежития. Это требования МГУ, а не общий список для всех вузов.',
    'Before travel, ask your faculty office about insurance and the medical documents listed by MSU. If you are under 18, confirm parental consent requirements for medical procedures and housing.',
    'https://international.msu.ru/before',
    { ...foreign, arrivalStatuses: ['preparing'] },
    35,
  ),
  action(
    'MSU',
    'MSU_DORM_MIGRATION',
    'first_three_days',
    'Передать документы на учёт через факультет МГУ',
    'Submit dormitory registration documents through your MSU faculty',
    'Если вы заселились в общежитие МГУ, обратитесь в иностранный отдел именно своего факультета на следующий рабочий день после приезда. Подготовьте паспорт, миграционную карту и их копии, справку общежития с адресом и комнатой либо договор найма. МГУ просит передать сведения в пределах трёх рабочих дней после въезда; это внутренний порядок подачи, не дата готовой регистрации. Получите подтверждение оформления.',
    'If you moved into an MSU dormitory, visit your own faculty international office on the next working day. Bring passport, migration card, copies and your dormitory address or contract. MSU requests submission within three working days of entry; this is not the date registration is completed. Collect the confirmation.',
    'https://international.msu.ru/after',
    { ...foreign, ...dorm, ...arrived },
    40,
  ),
  action(
    'MSU',
    'MSU_VISA_EXTENSION',
    'first_30_days',
    'Проверить продление учебной визы через факультет МГУ',
    'Check study visa renewal with your MSU faculty',
    'Если срок визы подходит к концу, МГУ просит передать комплект в иностранный отдел факультета не позднее чем за 30 дней до окончания. Уточните действующий список документов и пошлину у отдела: опубликованная страница старая, а вид дней не указан. Без подтверждённой даты окончания визы напоминание не вычисляется.',
    'If your visa is expiring, MSU asks you to submit documents to your faculty office at least 30 days before expiry. Confirm the current document list and fee; the published page is old and does not define the day type. No reminder is calculated without a confirmed visa expiry date.',
    'https://international.msu.ru/after',
    { ...foreign, entryModes: ['visa'] },
    60,
  ),

  action(
    'MEPHI',
    'MEPHI_ACCOUNT',
    'first_week',
    'Войти в личный кабинет и почту МИФИ',
    'Access your MEPhI account and email',
    'После приказа о зачислении зарегистрируйтесь по инструкции МИФИ на странице личного кабинета. Получите электронный идентификатор для студенческой почты и проверьте расписание. Если доступ ещё не выдан, уточните это в вузе; общего срока страница не устанавливает.',
    'After the admission order, follow the MEPhI account instructions. Get your student email identifier and check the timetable. If access has not been issued, ask the university; no general deadline is stated.',
    'https://mephi.ru/students/cab',
    { ...main },
    20,
  ),
  action(
    'MEPHI',
    'MEPHI_DORM_PACKAGE_2026',
    'pre_arrival',
    'Подготовить документы для общежития МИФИ',
    'Prepare MEPhI dormitory documents',
    'Если вам подтвердили место в московском общежитии на набор 2026, сверяйтесь с назначением института. Для первичного заселения страница МИФИ просит сканы паспорта и фото на белом фоне; для договора — паспорт и копию, фото 3×4, справку 086/у с отметкой дерматолога, прививочный сертификат; несовершеннолетнему — письменное согласие родителей. Адрес берите только из своего назначения.',
    'If your 2026 Moscow dormitory place is confirmed, follow your institute assignment. MEPhI lists passport scans and a white-background photo for initial move-in; for the contract, passport and copy, a 3×4 photo, medical certificate 086/u with dermatologist note, vaccination certificate and parental consent for minors. Use only your assigned address.',
    'https://mephi.ru/press/news/26379',
    { ...main, ...dorm, admissionYears: [2026] },
    35,
    2026,
  ),
  action(
    'MEPHI',
    'MEPHI_G106_REGISTRATION',
    'first_three_days',
    'Передать въездные документы в Г-106 МИФИ',
    'Submit entry documents to MEPhI G-106',
    'Если вы иностранный студент московского МИФИ и заселились в общежитие, обратитесь в Департамент международного сотрудничества, кабинет Г-106, в течение трёх рабочих дней после приезда. Возьмите паспорт, миграционную карту со штампом и учебную визу, если она нужна. Если после вступительных испытаний вы не выезжали из РФ, возьмите прежнюю регистрацию. После оформления заберите отрывную часть уведомления.',
    'If you are an international MEPhI Moscow student in a dormitory, visit the International Cooperation Department, room G-106, within three working days of arrival. Bring passport, stamped migration card and study visa if required. If you stayed in Russia after entrance exams, bring your previous registration. Collect the registration slip after processing.',
    'https://mephi.ru/foreign-nationals/migration-reg/migr-stud/postanovka-na-pervichnyy-migratsionnyy-uchet',
    { ...main, ...foreign, ...dorm, ...arrived },
    42,
  ),
  action(
    'MEPHI',
    'MEPHI_VISA_RENEWAL',
    'first_30_days',
    'Уточнить продление визы в Г-106 МИФИ',
    'Ask MEPhI G-106 about visa renewal',
    'Для многократной визы МИФИ просит обращаться в Г-106 за месяц до конца действующей визы. На странице названы паспорт, миграционная карта, матовое фото 3×4 и квитанция, которую выдают в Г-106. «За месяц» не превращается автоматически в дату без срока вашей визы и уточнения текущей инструкции.',
    'MEPhI asks students to visit G-106 about a multiple-entry visa one month before expiry. Its page lists passport, migration card, a matte 3×4 photo and the fee receipt issued there. This is not automatically converted to a date without your visa expiry and current instructions.',
    'https://mephi.ru/foreign-nationals/visa/stud/mnogokrat-visa',
    { ...main, ...foreign, entryModes: ['visa'] },
    65,
  ),

  action(
    'MIPT',
    'MIPT_CONFIRM_PROGRAM_LEVEL',
    'pre_arrival',
    'Уточнить программу МФТИ: базовое образование или магистратура?',
    'Confirm your MIPT programme level',
    'Какой у вас уровень программы: базовое высшее образование, магистратура или аспирантура? Укажите его в профиле: распределение мест в общежитии различается. Остальные известные дела останутся в плане. Если уровень программы неясен, спросите в приёмной комиссии МФТИ.',
    'Is your programme basic higher education, master’s or postgraduate? Set it in your profile: dormitory assignment differs. Your other known actions remain in the plan. If unsure, ask MIPT admissions.',
    'https://pk.mipt.ru/master/obshchezhitie-i-meditsinskoe-obsledovanie/',
    { ...dorm, programLevels: ['unknown'] },
    18,
  ),
  action(
    'MIPT',
    'MIPT_DORM_APPLICATION',
    'pre_arrival',
    'Заполнить анкету на общежитие МФТИ после приказа',
    'Apply for MIPT housing after admission',
    'После приказа о зачислении на программу базового высшего образования откройте личный кабинет МФТИ и заполните анкету на поселение. Передайте документы, дождитесь решения и назначения корпуса от ответственного за заселение; анкета сама по себе не означает предоставленное место. Если порядок непонятен, напишите в социальный деканат: socialdean@phystech.edu.',
    'After admission to a basic higher-education programme, fill in the housing form in your MIPT account. Submit the documents and wait for the housing officer to assign a building; the form does not guarantee a place. Ask socialdean@phystech.edu if the procedure is unclear.',
    'https://pk.mipt.ru/bachelor/obshchezhitie-i-meditsinskoe-obsledovanie/',
    { ...dorm, programLevels: ['bachelor_specialist'], housingStatuses: ['unknown', 'applied'] },
    20,
  ),
  action(
    'MIPT',
    'MIPT_MASTER_DORM_APPLICATION',
    'pre_arrival',
    'Уточнить место в общежитии МФТИ — магистратура и аспирантура',
    'Confirm MIPT master’s or postgraduate housing',
    'После приказа о зачислении заполните анкету на общежитие в личном кабинете. Для магистратуры и аспирантуры МФТИ распределяет свободные места после студентов базового высшего образования: анкета и поступление не гарантируют комнату. Дождитесь решения и личного назначения; вопросы направляйте в социальный деканат: socialdean@phystech.edu, +7 (495) 576-08-27.',
    'After admission, fill in the housing form in your MIPT account. Master’s and postgraduate students receive available places after basic higher-education students; the form and admission do not guarantee a room. Wait for a personal assignment, or contact socialdean@phystech.edu, +7 (495) 576-08-27.',
    'https://pk.mipt.ru/master/obshchezhitie-i-meditsinskoe-obsledovanie/',
    { ...dorm, programLevels: ['masters', 'postgraduate'], housingStatuses: ['unknown', 'applied'] },
    20,
  ),
  action(
    'MIPT',
    'MIPT_DORM_DOCUMENTS',
    'pre_arrival',
    'Подготовить пакет для общежития МФТИ',
    'Prepare MIPT dormitory documents',
    'Когда место назначено, подготовьте паспорт, медицинский полис и справку о флюорографии не старше 12 месяцев. Несовершеннолетнему нужно согласие представителя, льготнику — подтверждение льготы. Договор и адрес корпуса получите из персонального назначения МФТИ.',
    'When a place is assigned, prepare passport, health insurance and fluorography certificate no older than 12 months. Minors need guardian consent, priority applicants need supporting documents. Use your personal MIPT building assignment and contract.',
    'https://pk.mipt.ru/bachelor/obshchezhitie-i-meditsinskoe-obsledovanie/',
    { ...dorm, programLevels: ['bachelor_specialist'] },
    30,
  ),
  action(
    'MIPT',
    'MIPT_MASTER_DORM_DOCUMENTS',
    'pre_arrival',
    'Подготовить документы для общежития МФТИ — магистратура и аспирантура',
    'Prepare MIPT master’s or postgraduate dormitory documents',
    'После личного назначения корпуса подготовьте паспорт, медицинский полис и флюорографию не старше 12 месяцев; подтверждение льготы — при наличии. Договор заключайте по указанию ответственного за заселение. Если место ещё не назначено, сначала уточните результат распределения в социальном деканате.',
    'After your building is personally assigned, prepare your passport, health insurance and fluorography certificate no older than 12 months; provide priority evidence if applicable. Sign the housing contract as directed by the housing officer. If no place is assigned, first ask the social dean’s office about the result.',
    'https://pk.mipt.ru/master/obshchezhitie-i-meditsinskoe-obsledovanie/',
    { ...dorm, programLevels: ['masters', 'postgraduate'], housingStatuses: ['confirmed'] },
    30,
  ),
  action(
    'MIPT',
    'MIPT_PHYSICAL_EDUCATION',
    'first_week',
    'Получить справку о группе здоровья для физкультуры',
    'Get your physical-education health group certificate',
    'Если вы зачислены на программу базового высшего образования МФТИ, после зачисления получите справку с группой здоровья для занятий физкультурой. Это отдельная справка, не флюорография для общежития. Адрес сдачи и точный срок уточните в вузе.',
    'If you entered a MIPT basic higher-education programme, obtain a health-group certificate for physical education after enrollment. It is separate from the dormitory fluorography certificate. Confirm where and when to submit it.',
    'https://pk.mipt.ru/bachelor/obshchezhitie-i-meditsinskoe-obsledovanie/',
    { programLevels: ['bachelor_specialist'] },
    45,
  ),
  action(
    'MIPT',
    'MIPT_VISA_ARRIVAL',
    'first_three_days',
    'Сообщить МФТИ о визовом въезде',
    'Report visa-based arrival to MIPT',
    'После пересечения границы МФТИ просит обратиться в отдел международных связей, 312 Аудиторный корпус, и отправить на migrationservice@phystech.edu чёткие фотографии миграционной карты и всех страниц паспорта, включая пустые. Университет пишет «в течение двух дней», но вид дней не уточнён; обратитесь сразу и не считайте письмо готовой регистрацией.',
    'After entry, MIPT asks you to contact the international office in Academic Building room 312 and email clear images of the migration card and every passport page, including blank ones, to migrationservice@phystech.edu. The page says “within two days” without defining the day type; contact them promptly and obtain registration confirmation.',
    'https://pk.mipt.ru/foreign/',
    { ...foreign, entryModes: ['visa'], ...arrived },
    48,
  ),
  action(
    'MIPT',
    'MIPT_VISA_RENEWAL',
    'first_30_days',
    'Уточнить продление однократной визы МФТИ',
    'Ask MIPT about single-entry visa renewal',
    'МФТИ просит обратиться за 45 дней до окончания однократной визы в отдел международных связей, 312 Аудиторный корпус. Получите актуальный комплект документов у отдела; на странице нет полного списка и не указан вид дней. Без даты окончания визы срок не рассчитывается.',
    'MIPT asks students to visit the international office in Academic Building room 312, 45 days before a single-entry visa expires. Obtain the current document list there; the page does not specify the day type or a complete list. No date is calculated without the visa expiry.',
    'https://pk.mipt.ru/foreign/',
    { ...foreign, entryModes: ['visa'] },
    62,
  ),

  action(
    'HSE',
    'HSE_ACCOUNT_MAIL',
    'first_week',
    'Активировать почту и личный кабинет ВШЭ',
    'Activate HSE email and student account',
    'После отдельных писем с доступом войдите в студенческую почту и Единый личный кабинет. Проверьте телефон, личную почту и данные для студенческого билета в «ЯУчусь». Дату выдачи билета сообщает менеджер программы; универсального календарного срока нет.',
    'After receiving access emails, sign in to HSE student mail and the unified account. Check your phone, personal email and student-card details in the university service. Your programme manager gives the card collection date; no universal deadline is stated.',
    'https://www.hse.ru/studyspravka/start',
    { ...main },
    15,
  ),
  action(
    'HSE',
    'HSE_MOSCOW_RF_DOCUMENTS',
    'pre_arrival',
    'Подготовить пакет к направлению в общежитие ВШЭ',
    'Prepare documents for HSE Moscow housing',
    'Только если вам выдано направление на общежитие Москвы для набора 2026: возьмите паспорт и копию с регистрацией на одном листе, справку 086/у или распечатанную СЭМД-196, сертификат о прививках с копией, медицинский полис с копией. Приезжайте в назначенные лично вам адрес и дату.',
    'Only if you have a 2026 Moscow dormitory referral: bring passport and registration-page copy on one sheet, certificate 086/u or printed SEMD-196, vaccination certificate and copy, and insurance policy and copy. Go to your individually assigned address and date.',
    'https://www.hse.ru/dormoffice/zaseleniebak2026',
    {
      ...rf,
      ...main,
      ...dorm,
      admissionYears: [2026],
      programLevels: ['bachelor_specialist'],
      housingStatuses: ['confirmed'],
    },
    45,
    2026,
  ),
  action(
    'HSE',
    'HSE_MOSCOW_FOREIGN_INTAKE',
    'pre_arrival',
    'Сверить очный приём иностранного первокурсника ВШЭ',
    'Confirm HSE Moscow in-person international intake',
    'Для московского набора 2026 проверьте в личном кабинете, нужен ли вам очный визит с оригиналами документов в приёмную комиссию, Покровский бульвар, 11, корпус 10, кабинет D623. Перед визитом сверьте перечень с уже поданной заявкой: паспорт с переводом, документы об образовании, миграционная карта и фотографии могут потребоваться по вашему случаю.',
    'For the 2026 Moscow intake, check your applicant account for an in-person originals check at Pokrovsky Boulevard 11, building 10, room D623. Confirm the list against documents already submitted; passport translation, education documents, migration card and photos may apply.',
    'https://admissions.hse.ru/en/admission26',
    { ...foreign, ...main, admissionYears: [2026] },
    25,
    2026,
  ),
  action(
    'HSE',
    'HSE_MOSCOW_FOREIGN_DORM',
    'pre_arrival',
    'Получить личное направление на общежитие ВШЭ',
    'Obtain your personal HSE Moscow housing referral',
    'Для иностранного набора 2026 после очного этапа и приказа проверьте в личном кабинете заявление о потребности в жилье и персональное направление. В нём адрес, комната и дата. Место гарантировано только категориям, которые прямо названы ВШЭ; другим не обещайте его. Для заселения уточните пакет: паспорт, миграционная карта, страховой и медицинский документы; виза — лишь при визовом въезде.',
    'For the 2026 international intake, check your housing request and individual referral after the in-person stage and admission order. It gives your address, room and date. HSE guarantees a place only to specified categories. Confirm passport, migration, insurance and medical documents; visa only if applicable.',
    'https://www.hse.ru/dormoffice/internationalst2026',
    { ...foreign, ...main, ...dorm, admissionYears: [2026] },
    35,
    2026,
  ),
  action(
    'HSE',
    'HSE_MOSCOW_MIGRATION',
    'first_three_days',
    'Уточнить миграционные действия в центре ВШЭ',
    'Check migration steps at HSE Moscow',
    'После приезда обратитесь в центр визово-миграционного сопровождения ВШЭ: Покровский бульвар, 11, корпус D, кабинет D007; подача документов через центр «Студент», вход №5. Покажите паспорт, визу или миграционную карту и сведения о фактическом жилье. Контакт visa-registration@hse.ru. Сроки из старых памяток не становятся автоматически вашим правовым сроком.',
    'After arrival, visit the HSE visa and migration support centre at Pokrovsky Boulevard 11, building D, room D007; document service is at Student Centre entrance 5. Bring passport, visa or migration card and actual housing details. Contact visa-registration@hse.ru. Old guide dates are not automatically your legal deadline.',
    'https://istudents.hse.ru/en/entering',
    { ...foreign, ...main, ...arrived },
    48,
  ),
  action(
    'HSE',
    'HSE_SPB_HOUSING',
    'pre_arrival',
    'Дождаться направления на общежитие ВШЭ в Петербурге',
    'Wait for your HSE Saint Petersburg housing referral',
    'Если учитесь очно в кампусе Санкт-Петербург и запросили жильё, следите за студенческой почтой после приказа. В личном направлении будут адрес, дата и тип общежития. Для собственного/арендованного и Межвузовского студенческого городка пакеты документов различаются; уточните свой у отдела проживания: oop-spb@hse.ru.',
    'If you study full-time at HSE Saint Petersburg and requested housing, watch your email after admission. Your referral provides address, date and dormitory type. Document packs differ for university/rented housing and the inter-university campus; ask oop-spb@hse.ru.',
    'https://spb.hse.ru/dormitory/enrollee',
    { campusCodes: ['spb'], ...dorm, housingStatuses: ['unknown', 'applied'] },
    28,
  ),
  action(
    'HSE',
    'HSE_SPB_MIGRATION_DORM',
    'first_three_days',
    'Передать документы на учёт в ВШЭ Петербурга',
    'Submit migration documents to HSE Saint Petersburg',
    'Если вы иностранный студент и живёте в общежитии ВШЭ Петербурга, в день въезда или на следующий день обратитесь в миграционный центр: Кантемировская, 3, корпус 1, офис 1005. Возьмите паспорт и копии заполненных страниц, миграционную карту с копией и прежний учёт при наличии. Результат получите по сообщению на почту; это не срок завершения учёта.',
    'If you are an international student in an HSE Saint Petersburg dormitory, visit the migration centre on entry day or the next day: Kantemirovskaya 3, building 1, office 1005. Bring passport and copies of filled pages, migration card and copy, previous registration if any. Collect the result when notified.',
    'https://spb.hse.ru/io/migrdocs/',
    { ...foreign, ...dorm, ...arrived, campusCodes: ['spb'] },
    42,
  ),
  action(
    'HSE',
    'HSE_NN_DORM_APPLICATION',
    'pre_arrival',
    'Подать заявку на общежитие ВШЭ в Нижнем Новгороде',
    'Apply for HSE Nizhny Novgorod housing',
    'Отметьте потребность в жилье в кабинете абитуриента и подайте вузовскую заявку с копиями первой страницы паспорта и страницы с регистрацией. Проверьте опубликованный результат и личную дату заселения. Если кампания 2026 уже закрыта или вы приезжаете поздно, напишите mbalashova@hse.ru; корпус нельзя выбирать самостоятельно.',
    'Mark housing need in your applicant account and submit the university form with copies of the first passport page and registration page. Check the published result and your personal move-in date. If the 2026 campaign is closed or you arrive late, contact mbalashova@hse.ru; you cannot choose a building yourself.',
    'https://nnov.hse.ru/dormitory/order',
    { campusCodes: ['nnov'], ...dorm, housingStatuses: ['unknown'] },
    25,
  ),
  action(
    'HSE',
    'HSE_NN_DORM_DOCUMENTS',
    'pre_arrival',
    'Подготовить документы к заселению ВШЭ — Нижний Новгород',
    'Prepare HSE Nizhny Novgorod move-in documents',
    'Когда место и корпус назначены, возьмите паспорт и копию, медицинский полис и копию, копию 086/у с отметкой о флюорографии. Несовершеннолетнему нужны представитель при оформлении либо согласие на договор и регистрацию. Иностранцу дополнительно следует запросить миграционный пакет у кампуса; этот список не исчерпывающий.',
    'Once a place and building are assigned, bring passport and copy, insurance policy and copy, and a copy of certificate 086/u with fluorography. Minors need a representative or consent. International students should request additional migration documents; this list is not exhaustive.',
    'https://nnov.hse.ru/dormitory/order',
    { campusCodes: ['nnov'], ...dorm, housingStatuses: ['confirmed'] },
    35,
  ),
  action(
    'HSE',
    'HSE_NN_MIGRATION',
    'first_three_days',
    'Выбрать отдел ВШЭ Нижнего Новгорода для учёта',
    'Confirm the HSE Nizhny Novgorod registration office',
    'Если вы иностранный студент в общежитии, ВШЭ просит передать документы на следующий рабочий день после прибытия. У кампуса два офиса: Большая Печерская, 25/12, кабинет 412, и Львовская, 1в, кабинет 113. Сначала уточните свой офис и пакет по internationalnn@hse.ru; не езжайте по случайному адресу.',
    'If you are an international student in a dormitory, HSE asks for documents on the next working day after arrival. Its two offices are Bolshaya Pecherskaya 25/12 room 412 and Lvovskaya 1v room 113. First confirm your office and pack via internationalnn@hse.ru.',
    'https://nnov.hse.ru/intnn/istudents/migration',
    { ...foreign, ...dorm, ...arrived, campusCodes: ['nnov'] },
    45,
  ),
  action(
    'HSE',
    'HSE_PERM_DORM',
    'pre_arrival',
    'Проверить назначение места и подготовиться к заселению в ВШЭ — Пермь',
    'Check your HSE Perm housing assignment and prepare to move in',
    'Если место ещё не назначено, проверьте результат электронной заявки у кампуса; если оно уже подтверждено, новую заявку подавать не нужно. Для оформления договора вуз указывает бульвар Гагарина, 41, аудитория 137; это не обязательно адрес вашего проживания. Возьмите паспорт, оригинал 086/у и подтверждение прививок. Если вам нет 18 лет, уточните согласие представителя. Кампания 2026 могла закрыться — свяжитесь с AVZolin@hse.ru.',
    'If your place is not yet assigned, check your online application with the campus; if it is confirmed, do not apply again. The university signs contracts at Gagarina Boulevard 41, room 137; this is not necessarily your housing address. Bring passport, original 086/u and vaccination record. Minors should confirm guardian consent. If the 2026 campaign closed, contact AVZolin@hse.ru.',
    'https://perm.hse.ru/dormitory/order',
    { campusCodes: ['perm'], ...dorm },
    25,
  ),
  action(
    'HSE',
    'HSE_PERM_FOREIGN_PACK',
    'pre_arrival',
    'Уточнить расширенный пакет для общежития ВШЭ — Пермь',
    'Confirm the international HSE Perm housing pack',
    'Иностранному студенту нужно подтвердить бронирование у заведующего AVZolin@hse.ru и международного отдела interperm@hse.ru. Вузовские страницы расходятся по составу медицинских справок; до поездки запросите полный действующий комплект. Подготовьте паспорт с переводом, миграционную карту и имеющиеся медицинские документы; отправка письма не означает заселение.',
    'International students should confirm housing with AVZolin@hse.ru and interperm@hse.ru. University pages differ on medical documents; request the current complete pack before travel. Prepare passport translation, migration card and available medical records. Sending an email does not mean a place is assigned.',
    'https://perm.hse.ru/istudents/dormitory',
    { ...foreign, ...dorm, campusCodes: ['perm'] },
    35,
  ),

  action(
    'NSU',
    'NSU_FRESHMAN_MEETING',
    'pre_arrival',
    'Узнать дату встречи первокурсников НГУ',
    'Find your NSU first-year meeting',
    'После зачисления найдите дату вводной встречи именно своего факультета или спросите в деканате. На встрече объясняют группы, занятия и учебные материалы; единой даты для всего НГУ нет.',
    'After admission, find your own faculty’s introductory meeting date or ask the dean’s office. Staff explain groups, classes and study materials; there is no single university-wide date.',
    'https://education.nsu.ru/freshmen',
    {},
    15,
  ),
  action(
    'NSU',
    'NSU_CAMPUS_PASS',
    'first_week',
    'Получить электронный пропуск НГУ',
    'Get your NSU electronic pass',
    'Проверьте график своего факультета и возьмите паспорт в фойе блока №2 главного корпуса, Новосибирск, ул. Пирогова, 1. Пропуск нужен для входа и библиотеки. Если общая выдача уже прошла, уточните получение в деканате.',
    'Check your faculty schedule and bring your passport to the lobby of block 2, main building, Pirogova 1, Novosibirsk. The pass is used for access and the library. If the general issue period ended, ask your dean’s office.',
    'https://education.nsu.ru/freshmen',
    {},
    25,
  ),
  action(
    'NSU',
    'NSU_STUDENT_ACCOUNT',
    'first_week',
    'Получить учётную запись НГУ',
    'Set up your NSU student account',
    'Откройте инструкцию НГУ и используйте резервную почту, указанную при поступлении, чтобы задать пароль и войти в кабинет. Если инструкция или форма не открывается, смотрите памятку https://education.nsu.ru/freshmen либо напишите 4141@nsu.ru, указав ФИО и номер зачётной книжки; можно также обратиться с пропуском в кабинет 4222, 4215 или 3214. Пароль боту не отправляйте.',
    'Open the NSU instructions and use the recovery email from your admission form to set a password and enter your account. If the instructions or form will not open, use https://education.nsu.ru/freshmen or email 4141@nsu.ru with your name and student record number; you can also visit room 4222, 4215 or 3214 with your pass. Never send your password to this bot.',
    'https://help.nsu.ru/pages/viewpage.action?pageId=17174184',
    {},
    35,
  ),
  action(
    'NSU',
    'NSU_DORM_PACKAGE',
    'pre_arrival',
    'Собрать документы для общежития НГУ',
    'Collect NSU dormitory documents',
    'У деканата подтвердите своё общежитие и комнату. Памятка НГУ перечисляет паспорт, медицинский полис, прививки, СНИЛС, флюорографию не старше года, 086/у или СЭМД-196 и четыре фото 3×4; воинский документ — только при соответствующем статусе. Иностранному студенту следует подтвердить применимость отдельных документов в отделе сопровождения.',
    'Confirm your dormitory and room with your faculty. NSU lists passport, insurance, vaccinations, SNILS, fluorography within one year, certificate 086/u or SEMD-196 and four 3×4 photos; military documents only when applicable. International students should confirm which documents apply with support staff.',
    'https://education.nsu.ru/freshmen',
    { ...dorm },
    45,
  ),
  action(
    'NSU',
    'NSU_FOREIGN_SUPPORT',
    'first_three_days',
    'Уточнить свой порядок приезда в НГУ',
    'Confirm your arrival process at NSU',
    'Свяжитесь с отделом сопровождения иностранных студентов: главный корпус НГУ, кабинет 3268, телефон +7 (383) 363-43-56. Назовите программу, дату въезда, вид въезда и фактическое жильё; спросите, кто оформляет документы именно в вашем случае. Публичная памятка не даёт полного пакета для всех программ.',
    'Contact the international student support office, NSU main building room 3268, +7 (383) 363-43-56. Give programme, entry date and mode, and actual housing; ask who handles your documents. The public guide has no complete pack for every programme.',
    'https://education.nsu.ru/freshmen',
    { ...foreign },
    55,
  ),

  action(
    'SPBU',
    'SPBU_STUDENT_ACCOUNT',
    'first_week',
    'Получить доступ к кабинету СПбГУ',
    'Access your SPbU student account',
    'Бакалаврам и специалистам СПбГУ присылает данные на личную почту из заявления; магистрам и аспирантам — через кабинет поступающего. Войдите в студенческие сервисы и регулярно проверяйте почту. Если логин не пришёл, обратитесь в учебный отдел; пароль нашему боту не сообщайте.',
    'SPbU sends bachelor and specialist access to the personal email on the application; master’s and postgraduate students use the applicant account. Sign in and check student mail. If access is missing, contact the academic office; never share your password with this bot.',
    'https://guide.spbu.ru/studies',
    {},
    15,
  ),
  action(
    'SPBU',
    'SPBU_NOTIFY_ENTRY',
    'first_three_days',
    'Сообщить СПбГУ о въезде',
    'Notify SPbU about your entry',
    'Сразу после пересечения границы сообщите о прибытии на pvo@spbu.ru и в свой учебный отдел. Приложите копию миграционной карты, если она выдавалась. СПбГУ пишет «в течение двух дней» без уточнения вида дней; уведомление не заменяет учёт по адресу жилья.',
    'Immediately after crossing the border, notify pvo@spbu.ru and your academic office. Attach a migration card copy if one was issued. SPbU says “within two days” without defining the day type; this notice does not replace housing-address registration.',
    'https://guide.spbu.ru/foreigner',
    { ...foreign, ...arrived },
    22,
  ),
  action(
    'SPBU',
    'SPBU_DORM_REGISTRATION',
    'first_three_days',
    'Выбрать отдел СПбГУ по адресу своего общежития',
    'Choose the SPbU office for your actual dormitory',
    'Если живёте в общежитии СПбГУ, университет просит обратиться в миграционное управление в течение трёх рабочих дней после въезда. Для общежития в Петербурге адрес: Университетская наб., 7–9Б, Ректорский флигель, кабинет 102; для общежития в Петергофе: Ботаническая, 66, корпус 2, общежитие №10, кабинет 103. Выберите офис только по фактическому назначению жилья. Возьмите договор найма, паспорт с копиями страниц с отметками, миграционную карту с копией при наличии. Получите подтверждение оформления.',
    'If you live in a SPbU dormitory, the university requests a visit within three working days of entry. For Saint Petersburg housing use Universitetskaya Embankment 7–9B, room 102; for Peterhof housing use Botanicheskaya 66 building 2, dormitory 10, room 103. Choose only by your actual housing assignment. Bring contract, passport copies and migration card/copy if issued. Collect confirmation.',
    'https://guide.spbu.ru/foreigner',
    { ...foreign, ...dorm, ...arrived },
    38,
  ),
  action(
    'SPBU',
    'SPBU_PRIVATE_REGISTRATION',
    'first_three_days',
    'Согласовать учёт по частному адресу для СПбГУ',
    'Arrange registration at your private address for SPbU',
    'Если живёте вне общежития, договоритесь с собственником или администрацией гостиницы об учёте по фактическому адресу. После оформления отправьте подтверждение на pvo@spbu.ru и сообщите учебному отделу. СПбГУ также просит копию медицинской страховки. Университетский адрес не заменяет ваш адрес проживания.',
    'If you live outside a dormitory, arrange registration at the actual address with your landlord or hotel. Afterwards, send confirmation to pvo@spbu.ru and inform your academic office. SPbU also requests an insurance copy. The university address is not your residence address.',
    'https://guide.spbu.ru/foreigner',
    { ...foreign, ...privateHousing, ...arrived },
    42,
  ),
  action(
    'SPBU',
    'SPBU_VISA_EXPIRY',
    'first_30_days',
    'Проверить срок визы с СПбГУ',
    'Check visa expiry with SPbU',
    'Если ваша виза или разрешённое пребывание заканчивается, заранее запросите пакет у управления на pvo@spbu.ru. СПбГУ просит передавать документы не позднее 20 рабочих дней до окончания. Без введённой даты и проверки личного статуса автоматическая дата не создаётся.',
    'If your visa or permitted stay is expiring, request the current document pack at pvo@spbu.ru. SPbU asks for submission at least 20 working days before expiry. No automatic date is created without a confirmed personal expiry and status.',
    'https://guide.spbu.ru/foreigner',
    { ...foreign, entryModes: ['visa'] },
    60,
  ),

  action(
    'TSU',
    'TSU_DORM_RF_PACKAGE',
    'pre_arrival',
    'Собрать документы для общежития ТГУ — гражданину РФ',
    'Collect TSU dormitory documents for Russian citizens',
    'Сначала подтвердите место через свой деканат. Для заселения ТГУ просит паспорт и три копии нужных страниц, флюорографию не старше года с копией, справку об отсутствии чесотки и педикулёза, действующую три дня, и три фото 3×4. Несовершеннолетнему требуется нотариальная доверенность родителей для договора. Не выбирайте корпус без назначения.',
    'First confirm your place with your faculty. TSU lists passport and three copies of relevant pages, fluorography within one year and copy, a scabies/lice certificate valid for three days, and three 3×4 photos. Minors need notarised parental authorisation for the housing contract. Do not choose a building without assignment.',
    'https://info.abiturient.tsu.ru/ru/content/%D0%BE%D0%B1%D1%89%D0%B5%D0%B6%D0%B8%D1%82%D0%B8%D1%8F',
    { ...rf, ...dorm },
    25,
  ),
  action(
    'TSU',
    'TSU_DORM_CONTRACT',
    'first_week',
    'Заключить договор в назначенном общежитии ТГУ',
    'Sign the contract at your assigned TSU dormitory',
    'В свой назначенный день придите к коменданту именно назначенного общежития с комплектом документов, заключите договор найма, узнайте комнату у расселителя факультета и получите ключи. Общая дата на странице ТГУ не является вашим личным приглашением.',
    'On your assigned date, bring the document pack to the manager of your assigned dormitory, sign the housing contract, obtain your room from the faculty allocator and collect keys. The general date on the TSU page is not a personal appointment.',
    'https://info.abiturient.tsu.ru/ru/content/%D0%BE%D0%B1%D1%89%D0%B5%D0%B6%D0%B8%D1%82%D0%B8%D1%8F',
    { ...dorm, housingStatuses: ['confirmed'] },
    40,
  ),
  action(
    'TSU',
    'TSU_LAW_DORM_EXTRA',
    'pre_arrival',
    'Проверить отдельный пакет Юридического института ТГУ',
    'Check the TSU Law Institute housing pack',
    'Только для Юридического института при подтверждённом месте: факультет дополнительно называет справку о зачислении или выписку из приказа и справку из поликлиники №1 (пр. Ленина, 51) либо Межвузовской поликлиники (ул. Киевская, 74). На факультетской странице названы общежитие №5 и запасной «Парус», но окончательный адрес получите от деканата.',
    'Only for TSU Law Institute with a confirmed place: the faculty additionally lists an admission certificate/order extract and a medical certificate from clinic 1 (Lenina 51) or the inter-university clinic (Kievskaya 74). Its page names dormitory 5 and Parus as backup, but obtain your actual address from your faculty.',
    'https://ui.tsu.ru/?page_id=8237',
    { ...dorm, facultyCodes: ['tsu_law'], housingStatuses: ['confirmed'] },
    35,
  ),

  action(
    'ITMO',
    'ITMO_DORM_APPLICATION',
    'pre_arrival',
    'Заявить потребность в общежитии ИТМО',
    'Request ITMO dormitory housing',
    'При подаче через «Госуслуги» отметьте потребность в общежитии. В кабинете абитуриента загрузите флюорографию не старше 12 месяцев, сделанную в РФ, прививочную карту и СЭМД-196 либо 086/у; льготу подтвердите, если она есть. Заявка не означает место: ИТМО распределяет свободные комнаты по очереди.',
    'When applying through Gosuslugi, mark housing need. In the applicant account upload Russian fluorography within 12 months, vaccination record and SEMD-196 or 086/u; provide priority evidence if relevant. The request does not assign a place: ITMO allocates available rooms by queue.',
    'https://student.itmo.ru/ru/campus/dorms_and_aparts/booking',
    { ...dorm, housingStatuses: ['unknown'] },
    20,
  ),
  action(
    'ITMO',
    'ITMO_DORM_QUEUE',
    'pre_arrival',
    'Проверить очередь в общежитие ИТМО',
    'Check your ITMO housing queue',
    'После приказа дождитесь письма с ITMO.ID, войдите в my.itmo и откройте раздел «Общежития». Проверьте статус очереди и перенос медицинских документов; недостающие сведения внесите с датами прививок. Номер очереди появляется после всех приказов, а срок предоставления места заранее неизвестен.',
    'After admission, wait for the ITMO.ID email, sign in to my.itmo and open Dormitories. Check queue status and transferred medical documents; add missing vaccination dates. Queue position appears after all admission orders, and a room date cannot be predicted.',
    'https://student.itmo.ru/ru/campus/dorms_and_aparts/booking',
    { ...dorm, housingStatuses: ['unknown', 'applied'] },
    28,
  ),
  action(
    'ITMO',
    'ITMO_DORM_APPOINTMENT',
    'pre_arrival',
    'Выбрать время заселения после назначения ИТМО',
    'Choose move-in time after an ITMO assignment',
    'Только после письма о назначении места выберите дату и время во вкладке «Общежития» my.itmo. ИТМО просит сделать это за 48 часов от уведомления, а для Межвузовского студгородка (МСГ) — за 24 часа. Без подтверждённого письма и типа общежития приложение не вычисляет срок. Точный полный пакет спросите по campus@itmo.ru или +7 (812) 480-90-00, доб. 7: вложенные списки сейчас недоступны. Если назначен МСГ, справку для заселения выдаёт медпункт ИТМО (Кронверкский пр., 49, ауд. 2202; ул. Ломоносова, 9, ауд. 1001; medinform@itmo.ru).',
    'Only after an assignment email, choose a move-in slot in my.itmo. ITMO asks within 48 hours of notification, or 24 hours for the inter-university campus (MSG). Without the confirmed email and housing type, the app calculates no deadline. Ask campus@itmo.ru or +7 (812) 480-90-00 ext. 7 for the full pack: linked lists are unavailable. If assigned to MSG, obtain the housing certificate from the ITMO medical point (Kronverksky 49 room 2202; Lomonosova 9 room 1001; medinform@itmo.ru).',
    'https://student.itmo.ru/ru/campus/dorms_and_aparts/booking',
    { ...dorm, housingStatuses: ['confirmed'] },
    36,
  ),
  action(
    'ITMO',
    'ITMO_FOREIGN_PREARRIVAL',
    'pre_arrival',
    'Сообщить ИТМО сведения о въезде',
    'Tell ITMO your arrival details',
    'До поездки отправьте дату, время прибытия и пункт пересечения границы на omu@itmo.ru. ИТМО просит сделать это не позднее чем за 10 дней до въезда; это внутренний срок университета. Дождитесь ответного письма, а вопросы заселения задавайте int.students@itmo.ru.',
    'Before travel, email your arrival date, time and border-crossing point to omu@itmo.ru. ITMO asks at least 10 days before entry; this is its internal instruction. Wait for a response; housing questions go to int.students@itmo.ru.',
    'https://student.itmo.ru/ru/campus/dorms_and_aparts/booking',
    { ...foreign, arrivalStatuses: ['preparing'] },
    42,
  ),
  action(
    'ITMO',
    'ITMO_DORM_MIGRATION',
    'first_three_days',
    'Передать документы в миграционный отдел ИТМО',
    'Submit documents to the ITMO migration office',
    'Если фактически заселились в общежитие ИТМО, в день заселения или на следующий рабочий день обратитесь в отдел миграционного учёта: Санкт-Петербург, ул. Ломоносова, 9, офис 2139d. Возьмите документ въезда, миграционную карту, если она выдавалась, и договор платного обучения при наличии. Получите подтверждение регистрации после оформления.',
    'If you actually moved into an ITMO dormitory, visit the migration office on move-in day or the next working day: Lomonosova 9, office 2139d, Saint Petersburg. Bring entry document, migration card if issued, and paid-study contract if relevant. Collect confirmation after processing.',
    'https://student.itmo.ru/ru/campus/dorms_and_aparts/booking',
    { ...foreign, ...dorm, ...arrived },
    48,
  ),
  action(
    'ITMO',
    'ITMO_STUDENT_SERVICES',
    'first_week',
    'Проверить доступ к сервисам ИТМО',
    'Check access to ITMO student services',
    'После письма с ITMO.ID войдите в my.itmo: там можно проверить пропуск в корпуса и заказать справку об обучении или выписку из приказа. Если вы живёте дома или в частном жилье, миграционный шаг общежития к вам не относится.',
    'After receiving ITMO.ID, sign in to my.itmo to check campus access and request a study certificate or admission-order extract. If you live at home or privately, the dormitory migration step does not apply.',
    'https://student.itmo.ru/ru/documents/',
    {},
    55,
  ),

  action(
    'KFU',
    'KFU_DORM_APPLICATION',
    'pre_arrival',
    'Проверить заявку на общежитие КФУ',
    'Check your KFU dormitory application',
    'Для казанского кампуса проверьте отметку о потребности в жилье и статус заявления в кабинете абитуриента. После решения комиссии найдите личное назначение в списках; заявка сама по себе места не даёт. Если срок кампании 2026 прошёл, спросите отдел заселения о личном варианте, не полагайтесь на августовский график.',
    'For the Kazan campus, check your housing request and application status in the applicant account. After the commission decision, find your individual assignment; an application is not a place. If the 2026 campaign ended, ask housing staff about your case rather than using August dates.',
    'https://students.kpfu.ru/universiade-village/check-order/order',
    { ...main, ...dorm, housingStatuses: ['unknown', 'applied'] },
    20,
  ),
  action(
    'KFU',
    'KFU_DORM_RF_PACKAGE_2026',
    'pre_arrival',
    'Подготовить пакет общежития КФУ — гражданину РФ',
    'Prepare the 2026 KFU housing pack for Russian citizens',
    'Только при подтверждённом месте в Казани на набор 2026: проверьте университетский список из паспорта с копиями, ИНН, СНИЛС, полиса, флюорографии, RW-анализа, справок дерматовенеролога и терапевта, трёх фото 3×4; несовершеннолетнему нужно согласие родителей. Сроки действия медицинских справок разные — сверяйте их с персональным днём заезда.',
    'Only with a confirmed 2026 Kazan place: check the university list of passport and copies, tax and pension identifiers, insurance, fluorography, RW test, dermatologist and therapist certificates, three 3×4 photos, and parental consent for minors. Medical certificates have different validity windows; match them to your personal move-in date.',
    'https://students.kpfu.ru/universiade-village/check-order/junior-students',
    { ...rf, ...main, ...dorm, admissionYears: [2026], housingStatuses: ['confirmed'] },
    28,
    2026,
  ),
  action(
    'KFU',
    'KFU_DORM_FOREIGN_PACKAGE_2026',
    'pre_arrival',
    'Подготовить иностранный пакет общежития КФУ',
    'Prepare the 2026 international KFU housing pack',
    'Только при подтверждённом месте в Казани: запросите актуальный полный список у КФУ. Памятка 2026 называет паспорт и копии, ДМС, миграционную карту, RW-анализ и справку дерматовенеролога с переводом, флюорографию, заключение терапевта и три фото. Две страницы по-разному считают срок действия справки дерматовенеролога, поэтому не вычисляйте его автоматически.',
    'Only with a confirmed Kazan place: request the current full list from KFU. The 2026 guide lists passport and copies, insurance, migration card, translated RW and dermatologist tests, fluorography, therapist certificate and three photos. Two pages disagree on the dermatologist certificate validity; no date is calculated.',
    'https://students.kpfu.ru/universiade-village/population-of-foreigners',
    { ...foreign, ...main, ...dorm, admissionYears: [2026], housingStatuses: ['confirmed'] },
    28,
    2026,
  ),
  action(
    'KFU',
    'KFU_DORM_MIGRATION',
    'first_three_days',
    'Передать документы на учёт в КФУ после заселения',
    'Submit KFU registration documents after dormitory move-in',
    'Если вы иностранный студент и заселились в общежитие Казани, КФУ просит на следующий рабочий день явиться в Департамент внешних связей, ул. Гвардейская, 9. Возьмите паспорт, миграционную карту, договор найма и справку об обучении не старше 14 дней; визовому студенту — также визу и прежнюю регистрацию при наличии. Уточните кабинет перед визитом.',
    'If you are an international student in a Kazan dormitory, KFU asks you to visit the External Relations Department at Gvardeyskaya 9 on the next working day after move-in. Bring passport, migration card, housing contract and study certificate no older than 14 days; visa holders also bring visa and previous registration if any. Confirm the room before visiting.',
    'https://kpfu.ru/international/migracionnoe-soprovozhdenie-inostrannyh-grazhdan/bezvizovyi-vjezd',
    { ...foreign, ...main, ...dorm, ...arrived },
    42,
  ),
  action(
    'KFU',
    'KFU_PRIVATE_HOST',
    'first_three_days',
    'Получить ходатайство КФУ для учёта по частному адресу',
    'Obtain a KFU letter for private-address registration',
    'Если живёте в квартире в Казани, получите в Департаменте внешних связей КФУ, ул. Гвардейская, 9, ходатайство для принимающей стороны. Возьмите паспорт и подписанный договор найма по фактическому адресу. Собственник оформляет учёт; университет не регистрирует вас по адресу общежития.',
    'If you live in a Kazan apartment, obtain a support letter from KFU External Relations at Gvardeyskaya 9 for your host. Bring passport and signed rental contract for your actual address. The owner arranges registration; the university does not register you at a dormitory address.',
    'https://kpfu.ru/international/migracionnoe-soprovozhdenie-inostrannyh-grazhdan/bezvizovyi-vjezd',
    { ...foreign, ...main, ...privateHousing, ...arrived },
    48,
  ),

  action(
    'RUDN',
    'RUDN_DORM_PACKAGE',
    'pre_arrival',
    'Подготовить пакет к общежитию РУДН',
    'Prepare the RUDN dormitory pack',
    'После приказа и подтверждения места РУДН просит паспорт, две цветные фотографии 3×4, заключение Клинико-диагностического центра (КДЦ) о возможности проживания и студенческий билет либо временное удостоверение с номером. Иностранцу нужно также временное удостоверение международного департамента. Какие исследования нужны для заключения, уточните в КДЦ: Москва, ул. Миклухо-Маклая, 10; cdc@rudn.ru; +7 (495) 434-24-91. Вложенная памятка с анализами недоступна для проверки — не считайте этот список полным.',
    'After admission and housing confirmation, RUDN lists passport, two colour 3×4 photos, its Clinical Diagnostic Centre housing clearance, and student card or numbered temporary ID. International students also need a temporary international department ID. Ask the centre which examinations are needed: Miklukho-Maklaya 10, Moscow; cdc@rudn.ru; +7 (495) 434-24-91. The linked test memo could not be verified, so this is not a complete medical list.',
    'https://www.rudn.ru/life/accomodation',
    { ...dorm, housingStatuses: ['confirmed'] },
    20,
  ),
  action(
    'RUDN',
    'RUDN_PERMANENT_HOUSING',
    'first_week',
    'Получить направление на постоянное проживание РУДН',
    'Obtain permanent RUDN housing assignment',
    'С подтверждённым комплектом обратитесь в Управление по размещению, МФЦ РУДН, Москва, ул. Миклухо-Маклая, 6, цокольный этаж. Получите направление, обратитесь к специалисту по размещению, подпишите договор, оплатите выставленный счёт и затем получите ключи у заведующего или коменданта. Временное размещение не равно постоянному месту; миграционный учёт после заселения — отдельное дело.',
    'With your confirmed document pack, visit RUDN Accommodation Office at its service centre, Miklukho-Maklaya 6, basement. Obtain a referral, see the housing specialist, sign the contract, pay the issued bill, then collect keys from the manager. Temporary housing is not a permanent assignment; migration registration remains a separate task.',
    'https://www.rudn.ru/life/accomodation',
    { ...dorm, housingStatuses: ['confirmed'] },
    38,
  ),
  action(
    'RUDN',
    'RUDN_RF_TEMP_REGISTRATION',
    'first_30_days',
    'Оформить временную регистрацию в общежитии РУДН при необходимости',
    'Arrange RUDN dormitory temporary registration if needed',
    'Если вы гражданин РФ и живёте вне адреса постоянной регистрации более 90 дней, откройте lk.rudn.ru → «Сервисы» → «МФЦ РУДН» → «Регистрация граждан» и подайте заявку. Возьмите паспорт с копией и договор проживания с копией. Названные вузом 21 рабочий день — срок изготовления свидетельства, не срок подачи студентом.',
    'If you are a Russian citizen living away from your permanent registered address for over 90 days, use lk.rudn.ru → Services → RUDN service centre → citizen registration. Prepare passport and housing contract with copies. The university’s 21 working days describe processing, not your filing deadline.',
    'https://www.rudn.ru/life/multifunctional-center/uslugi-mfc-rudn/postanovka-na-pervichnyy-registracionnyy-uchet',
    { ...rf, ...dorm, mobilityStatuses: ['moving'] },
    50,
  ),
  action(
    'RUDN',
    'RUDN_FOREIGN_DORM_REGISTRATION',
    'first_three_days',
    'Подать заявку на миграционный учёт в МФЦ РУДН',
    'Apply for registration through the RUDN service centre',
    'Если живёте в общежитии РУДН, откройте lk.rudn.ru → «Сервисы» → «МФЦ РУДН» → «Регистрация граждан» → «Постановка на миграционный учёт». Приложите паспорт, миграционную карту и визу при визовом въезде; дополнительные документы зависят от статуса. После обработки получите результат лично. Указанные 14 рабочих дней — изготовление уведомления, не допустимый срок откладывать подачу.',
    'If you live in a RUDN dormitory, use lk.rudn.ru → Services → service centre → citizen registration → migration registration. Submit passport, migration card and visa for visa entry; other documents depend on status. Collect the result in person. The stated 14 working days is processing, not permission to delay filing.',
    'https://www.rudn.ru/life/multifunctional-center/uslugi-mfc-rudn/postanovka-na-pervichnyy-migracionnyy-uchet-dlya-stran-s-vizovymbezvizovym-rejimom',
    { ...foreign, ...dorm, ...arrived },
    45,
  ),
  action(
    'RUDN',
    'RUDN_PRIVATE_HODATAYSTVO',
    'first_three_days',
    'Получить ходатайство РУДН для частного жилья',
    'Obtain a RUDN letter for private housing',
    'Если вы живёте в частной квартире, собственник оформляет учёт по фактическому адресу. Для ходатайства РУДН обратитесь через МФЦ университета; возьмите паспорт, миграционную карту и прежнюю регистрацию, если она есть. Для впервые прибывшего без прежней регистрации уточните комплект у МФЦ. Один рабочий день на странице — срок изготовления ходатайства, не срок подачи учёта.',
    'If you live privately, the owner arranges registration at your actual address. Request a RUDN support letter through its service centre; prepare passport, migration card and previous registration if any. First arrivals without previous registration should confirm the pack. One working day on the page is letter processing, not the registration filing period.',
    'https://www.rudn.ru/life/multifunctional-center/uslugi-mfc-rudn/oformlenie-hodataystva-o-postanovke-na-migracionnyy-uchet',
    { ...foreign, ...privateHousing, ...arrived },
    48,
  ),
];
